import type { Kost } from './types';

export const INITIAL_CAMPUSES = ['UB', 'UM', 'UIN', 'UMM', 'POLINEMA', 'Unisma', 'ITN', 'Unmer'];
export const INITIAL_FACILITIES = ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'];

export const INITIAL_KOST_PROPERTIES: Kost[] = [
  {
    id: 'k1',
    name: 'Kost Putri Griya UB',
    gender: 'Putri',
    area: 'Sumbersari',
    address: 'Jl. Sumbersari No. 12, Sumbersari, Malang',
    pricePerMonth: 1500000,
    rating: 4.8,
    imageUrls: ['https://loremflickr.com/800/600/house,facade?lock=10', 'https://loremflickr.com/800/600/bedroom,interior?lock=11', 'https://loremflickr.com/800/600/bathroom,modern?lock=12'],
    description: 'Kost putri eksklusif dengan fasilitas lengkap, sangat dekat dengan gerbang Universitas Brawijaya. Lingkungan aman dan nyaman untuk belajar.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC', 'Dapur'],
    nearbyCampuses: ['UB', 'POLINEMA'],
    contactLink: 'https://wa.me/6281234567001',
  },
  {
    id: 'k2',
    name: 'Kost Putra UMM Tlogomas',
    gender: 'Putra',
    area: 'Tlogomas',
    address: 'Jl. Tlogomas No. 5, Tlogomas, Malang',
    pricePerMonth: 850000,
    rating: 4.5,
    imageUrls: ['https://loremflickr.com/800/600/house,facade?lock=20', 'https://loremflickr.com/800/600/bedroom,cozy?lock=21', 'https://loremflickr.com/800/600/kitchen,shared?lock=22'],
    description: 'Kost putra dengan harga terjangkau, lokasi strategis dekat kampus UMM terpadu. Akses mudah ke berbagai fasilitas umum.',
    facilities: ['Wifi', 'Dapur'],
    nearbyCampuses: ['UMM', 'Unisma'],
    contactLink: 'https://wa.me/6281234567002',
  },
  {
    id: 'k3',
    name: 'Kost Campur Omah UIN',
    gender: 'Campur',
    area: 'Gajayana',
    address: 'Jl. Gajayana No. 20, Gajayana, Malang',
    pricePerMonth: 1200000,
    rating: 4.6,
    imageUrls: ['https://loremflickr.com/800/600/apartment,facade?lock=30', 'https://loremflickr.com/800/600/bedroom,minimalist?lock=31', 'https://loremflickr.com/800/600/bathroom,clean?lock=32'],
    description: 'Kost campur yang modern dan bersih. Terletak di antara kampus UIN dan UM, cocok untuk mahasiswa dari kedua universitas.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'Water Heater'],
    nearbyCampuses: ['UIN', 'UM', 'UB'],
    contactLink: 'https://wa.me/6281234567003',
  },
  {
    id: 'k4',
    name: 'Kost Exclusive Polinema',
    gender: 'Campur',
    area: 'Soekarno-Hatta',
    address: 'Jl. Soekarno-Hatta Indah No. 1, Blimbing, Malang',
    pricePerMonth: 2000000,
    rating: 4.9,
    imageUrls: ['https://loremflickr.com/800/600/building,modern,facade?lock=40', 'https://loremflickr.com/800/600/bedroom,luxury?lock=41', 'https://loremflickr.com/800/600/gym,interior?lock=42'],
    description: 'Hunian kost premium dengan fasilitas hotel. Keamanan 24 jam dan lobi yang nyaman. Hanya 5 menit jalan kaki ke POLINEMA.',
    facilities: ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['POLINEMA', 'UB'],
    contactLink: 'https://wa.me/6281234567004',
  },
  {
    id: 'k5',
    name: 'Kost Ceria Unisma',
    gender: 'Putri',
    area: 'Dinoyo',
    address: 'Jl. MT Haryono Gg. X No. 8, Dinoyo, Malang',
    pricePerMonth: 700000,
    rating: 4.3,
    imageUrls: ['https://loremflickr.com/800/600/house,simple,facade?lock=50', 'https://loremflickr.com/800/600/bedroom,simple?lock=51', 'https://loremflickr.com/800/600/kitchen,interior?lock=52'],
    description: 'Kost sederhana dan homey, cocok untuk mahasiswa Unisma. Ibu kost ramah dan lingkungan sangat kondusif.',
    facilities: ['Wifi', 'Dapur'],
    nearbyCampuses: ['Unisma', 'UMM', 'ITN'],
    contactLink: 'https://wa.me/6281234567005',
  },
  {
    id: 'k6',
    name: 'Kost Idaman UM',
    gender: 'Putri',
    area: 'Klojen',
    address: 'Jl. Surabaya No. 15, Klojen, Malang',
    pricePerMonth: 1300000,
    rating: 4.7,
    imageUrls: ['https://loremflickr.com/800/600/house,cozy,facade?lock=60', 'https://loremflickr.com/800/600/bedroom,clean?lock=61', 'https://loremflickr.com/800/600/balcony,view?lock=62'],
    description: 'Kost putri di jantung kota Malang, sangat dekat dengan Universitas Negeri Malang. Akses angkutan umum sangat mudah.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC'],
    nearbyCampuses: ['UM', 'UB', 'Unmer'],
    contactLink: 'https://wa.me/6281234567006',
  },
   {
    id: 'k7',
    name: 'Pondok ITN Sigura-gura',
    gender: 'Putra',
    area: 'Sigura-gura',
    address: 'Jl. Sigura-gura Barat No. 3, Sigura-gura, Malang',
    pricePerMonth: 950000,
    rating: 4.4,
    imageUrls: ['https://loremflickr.com/800/600/house,facade?lock=70', 'https://loremflickr.com/800/600/bedroom,student?lock=71', 'https://loremflickr.com/800/600/desk,study,interior?lock=72'],
    description: 'Kost putra di kawasan populer Sigura-gura. Dekat dengan kampus ITN dan UIN. Banyak tempat makan dan kafe di sekitar.',
    facilities: ['Kamar mandi dalam', 'Wifi'],
    nearbyCampuses: ['ITN', 'UIN', 'UB'],
    contactLink: 'https://wa.me/6281234567007',
  },
  {
    id: 'k8',
    name: 'Wisma Merdeka',
    gender: 'Campur',
    area: 'Ijen',
    address: 'Jl. Ijen No. 77, Ijen, Malang',
    pricePerMonth: 1800000,
    rating: 4.8,
    imageUrls: ['https://loremflickr.com/800/600/house,classic,facade?lock=80', 'https://loremflickr.com/800/600/bedroom,elegant?lock=81', 'https://loremflickr.com/800/600/garden,backyard?lock=82'],
    description: 'Kost campur eksklusif di kawasan elit Ijen. Tenang dan asri, cocok untuk mahasiswa Unmer yang mencari kenyamanan lebih.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['Unmer', 'UM'],
    contactLink: 'https://wa.me/6281234567008',
  },
  {
    id: 'k9',
    name: 'Kost Ketawanggede Asri',
    gender: 'Campur',
    area: 'Ketawanggede',
    address: 'Jl. Ketawanggede No. 30, Ketawanggede, Malang',
    pricePerMonth: 1100000,
    rating: 4.6,
    imageUrls: ['https://loremflickr.com/800/600/house,tropical,facade?lock=90', 'https://loremflickr.com/800/600/bedroom,bright?lock=91', 'https://loremflickr.com/800/600/living,room,cozy?lock=92'],
    description: 'Lokasi super strategis, bisa jalan kaki ke gerbang utama UB. Kost campur dengan suasana tenang dan bersih.',
    facilities: ['Kamar mandi dalam', 'Wifi'],
    nearbyCampuses: ['UB', 'UM'],
    contactLink: 'https://wa.me/6281234567009',
  },
  {
    id: 'k10',
    name: 'Graha Mahasiswa Merjosari',
    gender: 'Putra',
    area: 'Merjosari',
    address: 'Jl. Joyo Grand No. 1, Merjosari, Malang',
    pricePerMonth: 750000,
    rating: 4.4,
    imageUrls: ['https://loremflickr.com/800/600/house,facade?lock=100', 'https://loremflickr.com/800/600/bedroom,simple?lock=101', 'https://loremflickr.com/800/600/kitchen,shared?lock=102'],
    description: 'Kost putra ekonomis di area Merjosari, dekat dengan kampus UIN dan Unisma. Fasilitas dasar lengkap.',
    facilities: ['Dapur', 'Wifi'],
    nearbyCampuses: ['UIN', 'Unisma', 'UMM'],
    contactLink: 'https://wa.me/6281234567010',
  },
  {
    id: 'k11',
    name: 'Betek Student House',
    gender: 'Putri',
    area: 'Betek',
    address: 'Jl. Mayjend Panjaitan Gg. 15, Betek, Malang',
    pricePerMonth: 900000,
    rating: 4.5,
    imageUrls: ['https://loremflickr.com/800/600/house,green,facade?lock=110', 'https://loremflickr.com/800/600/bedroom,cozy,interior?lock=111', 'https://loremflickr.com/800/600/bathroom,interior?lock=112'],
    description: 'Kost putri di lingkungan Betek yang ramai dan banyak pilihan kuliner. Jarak yang sangat dekat ke UB dan UM.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'Dapur'],
    nearbyCampuses: ['UB', 'UM'],
    contactLink: 'https://wa.me/6281234567011',
  },
  {
    id: 'k12',
    name: 'Soehat Premium Residence',
    gender: 'Campur',
    area: 'Soekarno-Hatta',
    address: 'Jl. Bunga Coklat No. 10, Soekarno-Hatta, Malang',
    pricePerMonth: 2200000,
    rating: 4.9,
    imageUrls: ['https://loremflickr.com/800/600/apartment,building,facade?lock=120', 'https://loremflickr.com/800/600/bedroom,modern,luxury?lock=121', 'https://loremflickr.com/800/600/lobby,hotel,interior?lock=122'],
    description: 'Kost campur mewah di jalan utama Soekarno-Hatta. Fasilitas lengkap setara apartemen, dekat dengan Polinema dan UB.',
    facilities: ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['POLINEMA', 'UB', 'ITN'],
    contactLink: 'https://wa.me/6281234567012',
  },
];