import type { Kost } from './types';

export const CAMPUSES = ['UB', 'UM', 'UIN', 'UMM', 'POLINEMA', 'Unisma', 'ITN', 'Unmer'];
export const FACILITIES = ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'];

export const INITIAL_KOST_PROPERTIES: Kost[] = [
  {
    id: 'k1',
    name: 'Kost Putri Griya UB',
    gender: 'Putri',
    area: 'Sumbersari',
    address: 'Jl. Sumbersari No. 12, Sumbersari, Malang',
    pricePerMonth: 1500000,
    rating: 4.8,
    imageUrls: ['https://picsum.photos/seed/kost1-ext/800/600', 'https://picsum.photos/seed/kost1-room/800/600', 'https://picsum.photos/seed/kost1-bath/800/600'],
    description: 'Kost putri eksklusif dengan fasilitas lengkap, sangat dekat dengan gerbang Universitas Brawijaya. Lingkungan aman dan nyaman untuk belajar.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC', 'Dapur'],
    nearbyCampuses: ['UB', 'POLINEMA'],
    contactLink: 'https://wa.me/6281234567001',
  },
  {
    id: 'k2',
    name: 'Kost Putra UMM Tlogomas',
    gender: 'Putra',
    area: 'Tlogomas',
    address: 'Jl. Tlogomas No. 5, Tlogomas, Malang',
    pricePerMonth: 850000,
    rating: 4.5,
    imageUrls: ['https://picsum.photos/seed/kost2-ext/800/600', 'https://picsum.photos/seed/kost2-room/800/600', 'https://picsum.photos/seed/kost2-common/800/600'],
    description: 'Kost putra dengan harga terjangkau, lokasi strategis dekat kampus UMM terpadu. Akses mudah ke berbagai fasilitas umum.',
    facilities: ['Wifi', 'Dapur'],
    nearbyCampuses: ['UMM', 'Unisma'],
    contactLink: 'https://wa.me/6281234567002',
  },
  {
    id: 'k3',
    name: 'Kost Campur Omah UIN',
    gender: 'Campur',
    area: 'Gajayana',
    address: 'Jl. Gajayana No. 20, Gajayana, Malang',
    pricePerMonth: 1200000,
    rating: 4.6,
    imageUrls: ['https://picsum.photos/seed/kost3-ext/800/600', 'https://picsum.photos/seed/kost3-room/800/600', 'https://picsum.photos/seed/kost3-bath/800/600'],
    description: 'Kost campur yang modern dan bersih. Terletak di antara kampus UIN dan UM, cocok untuk mahasiswa dari kedua universitas.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'Water Heater'],
    nearbyCampuses: ['UIN', 'UM', 'UB'],
    contactLink: 'https://wa.me/6281234567003',
  },
  {
    id: 'k4',
    name: 'Kost Exclusive Polinema',
    gender: 'Campur',
    area: 'Soekarno-Hatta',
    address: 'Jl. Soekarno-Hatta Indah No. 1, Blimbing, Malang',
    pricePerMonth: 2000000,
    rating: 4.9,
    imageUrls: ['https://picsum.photos/seed/kost4-ext/800/600', 'https://picsum.photos/seed/kost4-room/800/600', 'https://picsum.photos/seed/kost4-gym/800/600'],
    description: 'Hunian kost premium dengan fasilitas hotel. Keamanan 24 jam dan lobi yang nyaman. Hanya 5 menit jalan kaki ke POLINEMA.',
    facilities: ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['POLINEMA', 'UB'],
    contactLink: 'https://wa.me/6281234567004',
  },
  {
    id: 'k5',
    name: 'Kost Ceria Unisma',
    gender: 'Putri',
    area: 'Dinoyo',
    address: 'Jl. MT Haryono Gg. X No. 8, Dinoyo, Malang',
    pricePerMonth: 700000,
    rating: 4.3,
    imageUrls: ['https://picsum.photos/seed/kost5-ext/800/600', 'https://picsum.photos/seed/kost5-room/800/600', 'https://picsum.photos/seed/kost5-kitchen/800/600'],
    description: 'Kost sederhana dan homey, cocok untuk mahasiswa Unisma. Ibu kost ramah dan lingkungan sangat kondusif.',
    facilities: ['Wifi', 'Dapur'],
    nearbyCampuses: ['Unisma', 'UMM', 'ITN'],
    contactLink: 'https://wa.me/6281234567005',
  },
  {
    id: 'k6',
    name: 'Kost Idaman UM',
    gender: 'Putri',
    area: 'Klojen',
    address: 'Jl. Surabaya No. 15, Klojen, Malang',
    pricePerMonth: 1300000,
    rating: 4.7,
    imageUrls: ['https://picsum.photos/seed/kost6-ext/800/600', 'https://picsum.photos/seed/kost6-room/800/600', 'https://picsum.photos/seed/kost6-balcony/800/600'],
    description: 'Kost putri di jantung kota Malang, sangat dekat dengan Universitas Negeri Malang. Akses angkutan umum sangat mudah.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC'],
    nearbyCampuses: ['UM', 'UB', 'Unmer'],
    contactLink: 'https://wa.me/6281234567006',
  },
   {
    id: 'k7',
    name: 'Pondok ITN Sigura-gura',
    gender: 'Putra',
    area: 'Sigura-gura',
    address: 'Jl. Sigura-gura Barat No. 3, Sigura-gura, Malang',
    pricePerMonth: 950000,
    rating: 4.4,
    imageUrls: ['https://picsum.photos/seed/kost7-ext/800/600', 'https://picsum.photos/seed/kost7-room/800/600', 'https://picsum.photos/seed/kost7-desk/800/600'],
    description: 'Kost putra di kawasan populer Sigura-gura. Dekat dengan kampus ITN dan UIN. Banyak tempat makan dan kafe di sekitar.',
    facilities: ['Kamar mandi dalam', 'Wifi'],
    nearbyCampuses: ['ITN', 'UIN', 'UB'],
    contactLink: 'https://wa.me/6281234567007',
  },
  {
    id: 'k8',
    name: 'Wisma Merdeka',
    gender: 'Campur',
    area: 'Ijen',
    address: 'Jl. Ijen No. 77, Ijen, Malang',
    pricePerMonth: 1800000,
    rating: 4.8,
    imageUrls: ['https://picsum.photos/seed/kost8-ext/800/600', 'https://picsum.photos/seed/kost8-room/800/600', 'https://picsum.photos/seed/kost8-garden/800/600'],
    description: 'Kost campur eksklusif di kawasan elit Ijen. Tenang dan asri, cocok untuk mahasiswa Unmer yang mencari kenyamanan lebih.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['Unmer', 'UM'],
    contactLink: 'https://wa.me/6281234567008',
  },
  {
    id: 'k9',
    name: 'Kost Ketawanggede Asri',
    gender: 'Campur',
    area: 'Ketawanggede',
    address: 'Jl. Ketawanggede No. 30, Ketawanggede, Malang',
    pricePerMonth: 1100000,
    rating: 4.6,
    imageUrls: ['https://picsum.photos/seed/kost9-ext/800/600', 'https://picsum.photos/seed/kost9-room/800/600', 'https://picsum.photos/seed/kost9-common/800/600'],
    description: 'Lokasi super strategis, bisa jalan kaki ke gerbang utama UB. Kost campur dengan suasana tenang dan bersih.',
    facilities: ['Kamar mandi dalam', 'Wifi'],
    nearbyCampuses: ['UB', 'UM'],
    contactLink: 'https://wa.me/6281234567009',
  },
  {
    id: 'k10',
    name: 'Graha Mahasiswa Merjosari',
    gender: 'Putra',
    area: 'Merjosari',
    address: 'Jl. Joyo Grand No. 1, Merjosari, Malang',
    pricePerMonth: 750000,
    rating: 4.4,
    imageUrls: ['https://picsum.photos/seed/kost10-ext/800/600', 'https://picsum.photos/seed/kost10-room/800/600', 'https://picsum.photos/seed/kost10-kitchen/800/600'],
    description: 'Kost putra ekonomis di area Merjosari, dekat dengan kampus UIN dan Unisma. Fasilitas dasar lengkap.',
    facilities: ['Dapur', 'Wifi'],
    nearbyCampuses: ['UIN', 'Unisma', 'UMM'],
    contactLink: 'https://wa.me/6281234567010',
  },
  {
    id: 'k11',
    name: 'Betek Student House',
    gender: 'Putri',
    area: 'Betek',
    address: 'Jl. Mayjend Panjaitan Gg. 15, Betek, Malang',
    pricePerMonth: 900000,
    rating: 4.5,
    imageUrls: ['https://picsum.photos/seed/kost11-ext/800/600', 'https://picsum.photos/seed/kost11-room/800/600', 'https://picsum.photos/seed/kost11-bath/800/600'],
    description: 'Kost putri di lingkungan Betek yang ramai dan banyak pilihan kuliner. Jarak yang sangat dekat ke UB dan UM.',
    facilities: ['Kamar mandi dalam', 'Wifi', 'Dapur'],
    nearbyCampuses: ['UB', 'UM'],
    contactLink: 'https://wa.me/6281234567011',
  },
  {
    id: 'k12',
    name: 'Soehat Premium Residence',
    gender: 'Campur',
    area: 'Soekarno-Hatta',
    address: 'Jl. Bunga Coklat No. 10, Soekarno-Hatta, Malang',
    pricePerMonth: 2200000,
    rating: 4.9,
    imageUrls: ['https://picsum.photos/seed/kost12-ext/800/600', 'https://picsum.photos/seed/kost12-room/800/600', 'https://picsum.photos/seed/kost12-lobby/800/600'],
    description: 'Kost campur mewah di jalan utama Soekarno-Hatta. Fasilitas lengkap setara apartemen, dekat dengan Polinema dan UB.',
    facilities: ['Kamar mandi dalam', 'Dapur', 'Wifi', 'AC', 'Water Heater', 'CCTV'],
    nearbyCampuses: ['POLINEMA', 'UB', 'ITN'],
    contactLink: 'https://wa.me/6281234567012',
  },
];